### PR TITLE
Adding --naked paramater to uuid command.

### PR DESCRIPTION
**Pull request by erol-y**
It is useful to pass uuid information to linux kernel.
For example:
> "uuid --naked (hd3,1) | set myid="
> "kernel /vmlinuz root=uuid=%myid%"
Or passing directly:
> "uuid --naked (hd3,1) | kernel /vmlinuz root=uuid="

### CODE REVIEW

**Comment by steve6375** [comment]
Uuid (hd0,3)
set uuid=%?%

**Comment by erol-y** [comment]
yes, it is my fault. i missed this line in function:
"sprintf(ADDR_RET_STR,uuid_found);"

steve, do you have any word about colorized files?
color

**Comment by steve6375** [comment]
two colours = meaning is very clear  = files and folders.
why four colours?

**Comment by erol-y** [comment]
folders bootloaders linux-kernel and the others

**Comment by steve6375** [comment]
too confusing and not needed.

**Pull request closed without merging**
